// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGnp2HPSkBpmqEWB64FHJAy8uoeeg4ddQ',
    appId: '1:1086390775830:web:e5f54b81895f9899314537',
    messagingSenderId: '1086390775830',
    projectId: 'mapproject-e351d',
    authDomain: 'mapproject-e351d.firebaseapp.com',
    storageBucket: 'mapproject-e351d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuHHKMy9mI6j6MMDifNxl11kRr_7pm_Es',
    appId: '1:1086390775830:android:f7054afc91ec96fb314537',
    messagingSenderId: '1086390775830',
    projectId: 'mapproject-e351d',
    storageBucket: 'mapproject-e351d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Uslx9Zk6SL6KX7NaAdGTeo-ocmw-ehM',
    appId: '1:1086390775830:ios:89d432119d033e9f314537',
    messagingSenderId: '1086390775830',
    projectId: 'mapproject-e351d',
    storageBucket: 'mapproject-e351d.appspot.com',
    iosBundleId: 'com.example.mapsapp0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Uslx9Zk6SL6KX7NaAdGTeo-ocmw-ehM',
    appId: '1:1086390775830:ios:64219cdd82954d51314537',
    messagingSenderId: '1086390775830',
    projectId: 'mapproject-e351d',
    storageBucket: 'mapproject-e351d.appspot.com',
    iosBundleId: 'com.example.mapsapp0.RunnerTests',
  );
}
